// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestMsg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	TestMsg.proto

It has these top-level messages:
	TosChat
	TocChat
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TosChat struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *TosChat) Reset()                    { *m = TosChat{} }
func (m *TosChat) String() string            { return proto.CompactTextString(m) }
func (*TosChat) ProtoMessage()               {}
func (*TosChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TosChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TosChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TocChat struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *TocChat) Reset()                    { *m = TocChat{} }
func (m *TocChat) String() string            { return proto.CompactTextString(m) }
func (*TocChat) ProtoMessage()               {}
func (*TocChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TocChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TocChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*TosChat)(nil), "msg.TosChat")
	proto.RegisterType((*TocChat)(nil), "msg.TocChat")
}

func init() { proto.RegisterFile("TestMsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x49, 0x2d, 0x2e,
	0xf1, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x32,
	0xe7, 0x62, 0x0f, 0xc9, 0x2f, 0x76, 0xce, 0x48, 0x2c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x93, 0xf3,
	0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0xc0, 0xc2, 0x30, 0x2e, 0x44, 0x63, 0x32, 0xe9, 0x1a,
	0x93, 0xd8, 0xc0, 0xb6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x37, 0x01, 0x26, 0x8e,
	0x00, 0x00, 0x00,
}
